#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TASK_ROOT="${ROOT}/docs/tasks"
OUT_FILE="${ROOT}/docs/project-update.md"
DAILY_UNITS="${DAILY_UNITS:-6}"

lanes=(todo doing blocked done)

task_files() {
  local lane="$1"
  local lane_dir="${TASK_ROOT}/${lane}"
  if [ ! -d "${lane_dir}" ]; then
    return 0
  fi
  find "${lane_dir}" -maxdepth 1 -type f -name 'T*.md' | sort
}

task_id() {
  awk '/^## Task ID/{getline; gsub(/`/,"",$0); print $0; exit}' "$1"
}

task_slug() {
  awk '/^## Slug/{getline; gsub(/`/,"",$0); print $0; exit}' "$1"
}

task_units() {
  awk '/^- Unit Estimate: `/{gsub(/^- Unit Estimate: `|`$/,"",$0); print $0; exit}' "$1"
}

today="$(date +%Y-%m-%d)"

todo_count=0
todo_units=0
doing_count=0
doing_units=0
blocked_count=0
blocked_units=0
done_count=0
done_units=0

remaining_count=0
remaining_units=0

remaining_lines=()

for lane in "${lanes[@]}"; do
  while IFS= read -r f; do
    [ -f "${f}" ] || continue
    units="$(task_units "${f}")"
    id="$(task_id "${f}")"
    slug="$(task_slug "${f}")"
    case "${lane}" in
      todo)
        todo_count=$((todo_count + 1))
        todo_units=$((todo_units + units))
        remaining_count=$((remaining_count + 1))
        remaining_units=$((remaining_units + units))
        remaining_lines+=("- \`${id}\` \`${slug}\` (\`${units} units\`, \`TODO\`, \`READY\`)")
        ;;
      doing)
        doing_count=$((doing_count + 1))
        doing_units=$((doing_units + units))
        remaining_count=$((remaining_count + 1))
        remaining_units=$((remaining_units + units))
        remaining_lines+=("- \`${id}\` \`${slug}\` (\`${units} units\`, \`DOING\`, \`READY\`)")
        ;;
      blocked)
        blocked_count=$((blocked_count + 1))
        blocked_units=$((blocked_units + units))
        remaining_count=$((remaining_count + 1))
        remaining_units=$((remaining_units + units))
        remaining_lines+=("- \`${id}\` \`${slug}\` (\`${units} units\`, \`BLOCKED\`, \`BLOCKED\`)")
        ;;
      done)
        done_count=$((done_count + 1))
        done_units=$((done_units + units))
        ;;
    esac
  done < <(task_files "${lane}")
done

eta_days="$(awk -v u="${remaining_units}" -v d="${DAILY_UNITS}" 'BEGIN { if (d == 0) { print "N/A" } else { printf "%.1f", u / d } }')"

cat > "${OUT_FILE}" <<EOF
# Project Update

Date: \`${today}\`

> Generated by \`scripts/agents/update-project-update.sh\`

## Capacity Model
- Daily capacity: \`${DAILY_UNITS} units/day\`
- Size -> Units:
  - \`simple\` => \`1\`
  - \`standard\` => \`3\`
  - \`complex\` => \`6\`

## Deterministic Task State Rules
- Task state is determined only by folder location:
  - \`docs/tasks/todo\` => \`TODO\`
  - \`docs/tasks/doing\` => \`DOING\`
  - \`docs/tasks/blocked\` => \`BLOCKED\`
  - \`docs/tasks/done\` => \`DONE\`
- Stage in each task file must match folder lane.
- \`DONE\` requires completion record with AC+tests pass evidence.

## Visual Snapshot
\`\`\`mermaid
flowchart LR
  TODO["TODO\\n${todo_count} task(s)\\n${todo_units} units"] --> DOING["DOING\\n${doing_count} task(s)\\n${doing_units} units"]
  DOING --> BLOCKED["BLOCKED\\n${blocked_count} task(s)\\n${blocked_units} units"]
  DOING --> DONE["DONE\\n${done_count} task(s)\\n${done_units} units"]
\`\`\`

\`\`\`mermaid
pie showData
  title Unit Distribution (Current Board)
  "Done (${done_units})" : ${done_units}
  "Doing (${doing_units})" : ${doing_units}
  "Blocked (${blocked_units})" : ${blocked_units}
  "Todo (${todo_units})" : ${todo_units}
\`\`\`

## MVP Status
- Define MVP scope explicitly in your project docs and track completion against that scope.
- Current validation baseline should reference your project's required checks.

## PM Review Rhythm
- Weekly KPI review playbook: \`<link your project KPI review doc>\`

## Remaining Queue
EOF

if [ "${#remaining_lines[@]}" -eq 0 ]; then
  cat >> "${OUT_FILE}" <<'EOF'
- None
EOF
else
  printf '%s\n' "${remaining_lines[@]}" >> "${OUT_FILE}"
fi

cat >> "${OUT_FILE}" <<EOF

## Forecast (at ${DAILY_UNITS} units/day)
- Remaining tasks: \`${remaining_count}\`
- Remaining units: \`${remaining_units}\`
- ETA: \`${eta_days} day(s)\`

## Notes
- Task states are deterministically inferable from lane folder + lifecycle fields.
- Update this file by re-running:
  - \`scripts/agents/update-project-update.sh\`
EOF

echo "[PASS] Updated ${OUT_FILE}"
